### ISSUE TITLE
IOS devices, problem with player

### ISSUE THREAD

**Issue by michelson** [rauversion/rauversion-phx#106]
![Screen Shot 2022-10-31 at 10 35 29 PM](https://user-images.githubusercontent.com/11976/202559324-cbca6080-a9bf-4a86-8674-cf557de6e017.png)

**Comment by clsource** [comment]
This is problably due to the touch event that needs to be triggered by the user and not programatically in Safari iOS.

My recommendation would be to the upper left button to be a player on its own right, rather than just a trigger for the player below.
