### ISSUE TITLE
Error while trying to install

### ISSUE THREAD

**Issue by MauritzFunke** [rauversion/rauversion-phx#28]
So I tried to install the app but get an error when installing
```root@xxx:/opt/elexir/rauversion-phx# make install
mix deps.get
** (CompileError) config/config.exs:63: undefined function config_env/0
    (stdlib 3.14) lists.erl:1358: :lists.mapfoldl/3
    (elixir 1.10.3) expanding macro: Kernel.to_string/1
    config/config.exs:63: (file)
    (elixir 1.10.3) expanding macro: Config.import_config/1
    config/config.exs:63: (file)
make: *** [Makefile:4: install] Error 1
```

Edit: Trying to get it formatted right

**Comment by michelson** [comment]
Hi @MauritzFunke , could copy the entire error log?
also, try to rename the .env.example file to .env and to do the `mix deps.get `again.
which version of elixir do you have installed in your system?

**Comment by MauritzFunke** [comment]
That was the entire log
```
root@xxx:/opt/elexir/rauversion-phx# elixir -v
Erlang/OTP 23 [erts-11.1.8] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1]

Elixir 1.10.3 (compiled with Erlang/OTP 22)
root@xxx:/opt/elexir/rauversion-phx# make install
mix deps.get
** (CompileError) config/config.exs:63: undefined function config_env/0
    (stdlib 3.14) lists.erl:1358: :lists.mapfoldl/3
    (elixir 1.10.3) expanding macro: Kernel.to_string/1
    config/config.exs:63: (file)
    (elixir 1.10.3) expanding macro: Config.import_config/1
    config/config.exs:63: (file)
make: *** [Makefile:4: install] Error 1
```

**Comment by michelson** [comment]
super weird, what's your OS ?

I can confirm that is working with the following versions:

```
Erlang/OTP 24 [erts-12.3.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit] [dtrace]
Elixir 1.12.3 (compiled with Erlang/OTP 24)
```

**Comment by MauritzFunke** [comment]
Debian 11.4

**Comment by michelson** [comment]
try to update to OTP 24 and elixir 1.12.3, other users have this running on elixir 1.13 too

**Comment by michelson** [comment]
Hi @MauritzFunke, did you solve the installation?

**Comment by MauritzFunke** [comment]
@michelson I didnt have the time to try again. Will update in a few hours

**Comment by MauritzFunke** [comment]
So I managed to install it now. I'd suggest adding a part in your readme about all the config files, options and first steps when running (e.g. what is the live dashboard? I dont know the login data. I'd like to help you but I have 0 experience in elixir or erlang.

**Comment by michelson** [comment]
Hi @MauritzFunke , yeah some documentation is needed, the live dashboard right now has a hardcoded login that can be seen on the router, we need to add some config to override the auth credentials. from env!

Please eif you see that there is something missing on the readme please go ahead and submit a PR, also feel free to ask us any questions regarding the elixir and the platform in general.
