### ISSUE TITLE
Add Support for local storage

### ISSUE THREAD

**Issue by PhoenixSheppy** [rauversion/rauversion-phx#35]
As the title says, please add support for local storage.

I personally don't use S3, but the option to use solutions like MINIO or local VM / LXC storage would be nice.

**Comment by michelson** [comment]
Hi, As MINIO is a compatible S3 you can use it as a replacement storage. Also you can set up a "local" disk storage.

**Comment by PhoenixSheppy** [comment]
What are the steps to setup a local disk storage? I didn't see anything in the .env file.

**Comment by PhoenixSheppy** [comment]
> Hi, As MINIO is a compatible S3 you can use it as a replacement storage. Also you can set up a "local" disk storage.

@michelson What are the steps to configure local disk storage? I didn't see anything in the .env file when initially configuring.
